version: '2'

services:
        payment-gateway:
                image: ducatus-payment-gateway
                volumes:
                        - ./public:/usr/src/app/public
                ports:
                        - 3030:3030
                links:
                        - redis
        redis:
                image: redis
                ports:
                        - 6379:6379
