version: '2'

services:
        payment-gateway:
                image: ducatus-payment-gateway
                ports:
                        - 3030:3030
                links:
                        - redis
                
        nginx:
                image: nginx
                #restart: always
                ports:
                        - 443:443
                        - 80:80
                links:
                        - payment-gateway
                volumes:
                        - ./nginx/conf.d:/etc/nginx/conf.d
                        - ./nginx/keys:/etc/nginx/keys
                        - ./nginx/.htpasswd:/etc/nginx/.htpasswd
                        - ./www:/srv/

        redis:
                image: redis
                ports:
                        - 6379:6379
